### ISSUE TITLE
NetatmoConnectionProvider not included in NuGet

### ISSUE THREAD

**Issue by punthoofd07** [philipdaubmeier/GraphIoT#1]
Hi, 
First of thanks a lot for your work and effort. 
I added the nuget and followed the readme in order to get the first results. 

It looks like the NetatmoConnectionProvider is not included in the Nuget. 
var netatmoConnProvider = new NetatmoConnectionProvider()

I included the following namespaces and it should be included in .Network if I'm right? 
@using PhilipDaubmeier.NetatmoClient
@using PhilipDaubmeier.NetatmoClient.Model.Auth
@using PhilipDaubmeier.NetatmoClient.Model.WeatherStation
@using PhilipDaubmeier.NetatmoClient.Model.Core
@using PhilipDaubmeier.NetatmoClient.Model.HomeData
@using PhilipDaubmeier.NetatmoClient.Network

Could you please check? 
Thanks

**Comment by philipdaubmeier** [comment]
Hi, 
It is included, and yes your includes seem correct as well. However, the NetatmoConnectionProvider constructor requires a NetatmoAuth object. Sorry, I have to adjust the example here - it has the same mistake.

**Comment by punthoofd07** [comment]
Hi, 

Thanks, I imported all files in my project and it seems to work now. Indeed, it needs it: 
var AuthData = new NetatmoAuth("user", "pswd");
var netatmoConnProvider = new NetatmoConnectionProvider(AuthData) 

However, I still think the nuget is not the latest build?

**Comment by philipdaubmeier** [comment]
Your absolutely right - I checked the nuget release date and looked back at the git history, the NetatmoConnectionProvider Default implementation was not included there yet.

I just released a new version 1.3.0 of the nuget package with the latest code revision and updated the example code.

Thanks for pointing it out!

**Comment by punthoofd07** [comment]
Great! Thank you. Case closed
