### ISSUE TITLE
CO2 is null

### ISSUE THREAD

**Issue by punthoofd07** [philipdaubmeier/GraphIoT#2]
Hi again, 

Thanks for the Nuget update yesterday. One other minor thing that I found out is that the reported CO2 by the weather base station is null. 
weatherStation.Devices[0].DashboardData.CO2 -> results in null. 
Other data is coming through just fine. 
This is info that I'm getting from my weather base station.

**Comment by philipdaubmeier** [comment]
I'll have a look at it.

In the meantime: can you have a look at the module name of your `Devices[0]` and check if it is capable of measuring CO₂? The outdoor module for example does not have a CO₂ sensor.

**Comment by philipdaubmeier** [comment]
I just see, `Devices[0]` is the base station, not a module. I can reproduce the issue now - let me fix that. I did not notice it due to only using the `GetMeasure` method.

**Comment by philipdaubmeier** [comment]
Fixed it and uploaded a new version 1.4.1 of the nuget package that should solve the problem. Should be visible in a few minutes.

Thanks for reporting!

**Comment by punthoofd07** [comment]
Hi, 
Thanks a lot for your time and effort! Confirmed all is working now.
