### ISSUE TITLE
More information about failing Netamo requests

### ISSUE THREAD

**Issue by Abrissirba** [philipdaubmeier/GraphIoT#5]
Hi,  

First I would like to thank you for this amazing project! I am using the NetatmoWebClient in a project and it works really well.

One thing I would like is more information in the exception about why the call the the api is failing. I created a pull request, https://github.com/philipdaubmeier/GraphIoT/pull/4, that shows what I have in mind.

**Comment by philipdaubmeier** [comment]
Thanks for the kind words and thanks already for contributing! I'll have a look at it. Rich error information is definitely an important thing to have and makes total sense to improve on the library.

**Comment by philipdaubmeier** [comment]
Hi Abrissirba, I have refined the code a little bit, added unit tests and merged it back in - thanks again for contributing!

**Comment by Abrissirba** [comment]
Awesome! Definitly well motivated refinements :)
